members/urls.py
from django.urls import path
from .views import UserRegisterView

urlpatterns = [
	path('register/', UserRegisterView.as_view(), name='register'),
]

quiz/urls.py
from django.urls import path
from .views import (
	home_view,
	result_view,
	create_quiz,
	add_question,
	question_view,
	question_detail_view,
	save_answer_view,
)

app_name = 'quiz'

urlpatterns = [
	path('', home_view, name='home_view'),
	path('result/', result_view, name='result_view'),
	path('create/', create_quiz, name='create_quiz'),
	path('add/', add_question, name='add_question'),
	path('<pk>/', question_view, name='question_view'),
	path('<pk>/detail/', question_detail_view, name='question_detail_view'),
	path('<pk>/save/', save_answer_view, name='save_answer_view'),
]

quiz_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls', namespace='quiz')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/models.py
from django.db import models

# Create your models here.

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import random

TOPIC_CHOICES = (
	('Computer Science', 'Computer Science'),
	('Math and Logic', 'Math and Logic'),
	('Language Learning', 'Language Learning'),
	('Health', 'Health'),
	('Others', 'Others'),
)


class Topic(models.Model):
	topic_title = models.CharField(max_length=30, choices=TOPIC_CHOICES)

	def __str__(self):
		return str(self.topic_title)


class Quiz(models.Model):
	quiz_title = models.CharField(max_length=200)
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	time = models.PositiveIntegerField(help_text='duration of the quiz in minutes')
	created_by = models.ForeignKey(User, on_delete=models.CASCADE)
	created_time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.quiz_title)

	def get_questions(self):
		questions = list(self.question_set.all())
		random.shuffle(questions)
		return questions

	class Meta:
		verbose_name_plural = 'Quizzes'
		ordering = ("-created_time",)


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
	correct_num = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
	option_one = models.CharField(max_length=200)
	option_two = models.CharField(max_length=200)
	option_three = models.CharField(max_length=200)
	option_four = models.CharField(max_length=200)

	def __str__(self):
		return f"{self.question_text} - correct: {self.correct_num}"


class Result(models.Model):
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
	score = models.FloatField()
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.quiz} - {self.user} - {self.score}% - {self.created}"

quiz/forms.py
from django import forms
from .models import Quiz, Question

class QuizForm(forms.ModelForm):
	class Meta:
		model = Quiz
		exclude = ['created_by']


class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		exclude = ['quiz']

members/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class UserRegisterView(generic.CreateView):
	form_class = UserCreationForm
	template_name = 'registration/register.html'
	success_url = reverse_lazy('login')

quiz/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count
from .models import Topic, Quiz, Question, Result
from .forms import QuizForm, QuestionForm


def home_view(request):
	quiz = Quiz.objects.annotate(number_of_question=Count('question'))
	quiz = quiz.order_by("-created_time").all()
	paginator = Paginator(quiz, 6)
	page_number = request.GET.get('page')
	objects = paginator.get_page(page_number)
	form1 = QuizForm()
	form2 = QuestionForm()
	context = {
		'objects': objects,
		'form1': form1,
		'form2': form2,
	}

	return render(request, 'quiz/main.html', context)
	

@login_required
def result_view(request):
	results = Result.objects.filter(user=request.user)
	results = results.order_by("-created").all()
	return render(request, 'quiz/result.html', {'results': results})


@login_required
def create_quiz(request):
	if request.is_ajax():
		form = QuizForm(request.POST)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.created_by = request.user
			instance.save()
			return JsonResponse({
				'quiz_title': instance.quiz_title,
				'topic': instance.topic.topic_title,
				'time': instance.time,
				'created_by': instance.created_by.username,
				'id': instance.id
			})


@login_required
def add_question(request):
	if request.is_ajax():
		form = QuestionForm(request.POST)
		if form.is_valid():
			pk = request.POST.get('pk')
			quiz = Quiz.objects.get(pk=pk)
			instance = form.save(commit=False)
			instance.quiz = quiz
			instance.save()
			return JsonResponse({})


def question_view(request, pk):
	quiz = Quiz.objects.get(pk=pk)
	questions = quiz.get_questions()
	return render(request, 'quiz/question.html', 
		{
		'quiz': quiz,
		'que':  questions,
		}
	)


def question_detail_view(request, pk):
	quiz = Quiz.objects.get(pk=pk)
	ques = quiz.get_questions()
	questions = []
	for q in ques:
		ques_answers = [
			q.option_one,
			q.option_two,
			q.option_three,
			q.option_four
		]
		questions.append({q.question_text: ques_answers})

	return JsonResponse({
		'time': quiz.time,
		'questions': questions,
	})


def save_answer_view(request, pk):
	if request.is_ajax():
		answer = request.POST
		answer_ = dict(answer.lists())
		answer_.pop('csrfmiddlewaretoken')
		quiz = Quiz.objects.get(pk=pk)
		questions = [
			Question.objects.get(question_text=key, quiz=quiz)
			for key in answer_.keys()
		]

		score = 0
		results = []
		for q in questions:
			message = ""
			ans = answer_[q.question_text][0]
			options = {
				1: q.option_one,
				2: q.option_two,
				3: q.option_three,
				4: q.option_four
			}
			if (ans == options[q.correct_num]):
				score += 1
				message = "Correct!"
			else:
				message = f"Your answer: {ans}, Correct: {q.correct_num} - {options[q.correct_num]}"
			results.append({str(q.question_text): message})
		num_of_q = len(quiz.get_questions())
		score_ = round(score * 100 / num_of_q, 2)

		# If user logged in, save the result
		if request.user.is_authenticated:
			Result.objects.create(
				quiz=quiz,
				user=request.user,
				score=score_
			)

		return JsonResponse({'results': results, 'score': score_})

quiz/templates/quiz/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- favicon -->
	<link rel="icon" type="image/png" href="{% static 'quiz/img/favicon.ico' %}"/>

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

	<!-- Custom css -->
	<link rel="stylesheet" href="{% static 'quiz/css/style.css' %}">

	<!-- Custom js -->
	<script src="{% static 'quiz/js/functions.js' %}" defer></script>
	{% block scripts %}
	{% endblock %}

	<title>{% block title %}{% endblock %}</title>
</head>
<body>

	<!-- Navbar -->
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'quiz:home_view' %}">Manabit | {% block page-title %}{% endblock %}</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
	      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	      	{% if user.is_authenticated %}
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'quiz:result_view' %}">Results</a>
		        </li>
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
		        </li>
	      	{% else %}
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'register' %}">Register</a>
		        </li>
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'login' %}">Login</a>
		        </li>
	      	{% endif %}
	      </ul>
	    </div>
	  </div>
	</nav>

	<div class="container mt-3">
		{% block content %}
		{% endblock %}
	</div>


	<!-- JavaScript Bundle with Popper -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</body>
</html>

quiz/templates/quiz/main.html
{% extends 'quiz/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
  <script src="{% static 'quiz/js/main.js' %}" defer></script>
{% endblock %}

{% block title %}
Manabit
{% endblock %}

{% block page-title %}
Quiz List
{% endblock %}

{% block content %}

<div class="container" id="quiz-list-view">
  <div id="alert-box"></div>

  {% if user.is_authenticated %}
    <!-- Button trigger create quiz modal -->
    <button type="button" class="btn btn-outline-light mb-2" data-bs-toggle="modal" data-bs-target="#createQuiz">
    create quiz
    </button>
  {% endif %}

  <div class="row row-cols-1 row-cols-md-3 g-4" id="quiz-card">

    {% for obj in objects %}
    
    <!-- Card -->
      <div class="col">
        <div class="card">
          <div class="card-body">
            <div class="card-header text-center">{{obj.quiz_title}}</div>
            <div class="card-text text-left">
              <dl>
                <dt>Number of questions</dt>
                <dd id="numq-card-{{obj.id}}">{{obj.number_of_question}}</dd>
                <dt>Duration</dt>
                <dd>{{obj.time}} min(s)</dd>
                <dt>Created by</dt>
                <dd>{{obj.created_by}}</dd>
              </dl>
            </div>

            <!-- Button trigger each quiz start modal -->
            <button
              type="button"
              class="btn btn-secondary modal-button start-modal" 
              data-pk="{{ obj.pk }}"
              data-quiz="{{ obj.quiz_title }}"
              data-bs-toggle="modal" 
              data-bs-target="#quizStartModal"
            >
            start
            </button>
            {% if request.user == obj.created_by %}
              <button
              type="button"
              class="btn btn-outline-success modal-button add-modal" 
              data-pk="{{ obj.pk }}"
              data-quiz="{{ obj.quiz_title }}"
              data-bs-toggle="modal"
              data-bs-target="#addQuestion"
              >
              add
              </button>
            {% endif %}
          </div>
          <div class="card-footer text-center">
            <small class="text-muted">{{obj.topic}}</small>
          </div>
        </div>
      </div>

    {% endfor %}
  </div>
</div>

<!-- Pagination -->
<div class="container p-4">
  <ul class="pagination justify-content-center">
      {% if objects.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ objects.previous_page_number }}">&laquo;</a></li>
      {% else %}
          <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
      {% endif %}
      {% for i in objects.paginator.page_range %}
          {% if objects.number == i %}
              <li class="page-item active"><span class="page-link">{{ i }}</li>
          {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
      {% endfor %}
      {% if objects.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ objects.next_page_number }}">&raquo;</a></li>
      {% else %}
          <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
      {% endif %}
  </ul>
</div>

<!-- Create quiz modal -->
<div class="modal fade" id="createQuiz" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create quiz</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="quiz-form">
          {% csrf_token %}
          {{ form1|crispy }}
          <div class="modal-footer">
            <button type="button" class="btn btn-light" data-bs-dismiss="modal">close</button>
            <button type="submit" class="btn btn-info">create</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Quiz start modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalTitle"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you ready to start?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">no</button>
        <button type="button" id="start-button" class="btn btn-info">yes</button>
      </div>
    </div>
  </div>
</div>

<!-- Add question modal -->
<div class="modal fade" id="addQuestion" tabindex="-1" aria-labelledby="addModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addModal"></h5>

        
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="add-form" data-form-id="">
          {% csrf_token %}
          {{ form2|crispy }}
          <div class="modal-footer">
            <button type="button" class="btn btn-light" data-bs-dismiss="modal">close</button>
            <button type="submit" class="btn btn-info">add</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

quiz/templates/quiz/question.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block scripts %}
	<script src="{% static 'quiz/js/question.js' %}" defer></script>
{% endblock %}

{% block title %}
{{ quiz.quiz_title }}
{% endblock %}

{% block page-title %}
{{ quiz.quiz_title }}
{% endblock %}

{% block content %}

<div>
	<h3> <span class=" time-left">00:00</span></h3>
</div>
<br>
<a href="{% url 'quiz:home_view' %}" button class="btn btn-light mt-3 mb-3">back</a>
<div id="alert-box"></div>

<form id="quiz-form" class="mt-3 mb-3">
	{% csrf_token %}
	<div id="quiz-box"></div>
	<button type="submit" class="btn btn-info mt-3">save</button>
</form>

{% endblock %}

quiz/templates/quiz/result.html
{% extends 'quiz/base.html' %}

{% block title %}
Results
{% endblock title %}

{% block page-title %}
Results
{% endblock %}

{% block content %}

<table class="table result-table">
  <thead>
    <tr class="table">
      <th scope="col">Quiz</th>
      <th scope="col">Score</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  {% for result in results %}
  <tbody>
  	{% if result.score > 60 %}
    	<tr class="table">
    {% else %}
    	<tr class="table-secondary">
    {% endif %}
      	<td>{{result.quiz}}</td>
      	<td>{{result.score}}</td>
      	<td>{{result.created}}</td>
    	</tr>
  </tbody>
  {% endfor %}
</table>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- favicon -->
	<link rel="icon" type="image/png" href="{% static 'favicon.ico' %}"/>

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

	<!-- Custom css -->
	<link rel="stylesheet" href="{% static 'style.css' %}">

	<!-- Custom js -->
	<script src="{% static 'functions.js' %}" defer></script>
	{% block scripts %}
	{% endblock %}

	<title>{% block title %}{% endblock %}</title>
</head>
<body>

	<!-- Navbar -->
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'quiz:home_view' %}">Manabit | {% block page-title %}{% endblock %}</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
	      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	      	{% if user.is_authenticated %}
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'quiz:result_view' %}">Results</a>
		        </li>
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
		        </li>
	      	{% else %}
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'register' %}">Register</a>
		        </li>
		        <li class="nav-item">
		          <a class="nav-link" href="{% url 'login' %}">Login</a>
		        </li>
	      	{% endif %}
	      </ul>
	    </div>
	  </div>
	</nav>

	<div class="container mt-3">
		{% block content %}
		{% endblock %}
	</div>


	<!-- JavaScript Bundle with Popper -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</body>
</html>